In [1]:
import pandas as pd

In [5]:
rape_victim_2018= pd.read_csv(r'Rape_analysis2018-2022\\NCRB_CII_2018_rape_victim.csv')
rape_victim_2019=pd.read_csv(r'Rape_analysis2018-2022\\NCRB_CII-2019_rape victim.csv')
rape_victim_2020= pd.read_csv(r'Rape_analysis2018-2022\\NCRB_2020_rape victim.csv')
rape_victim_2021=pd.read_csv(r'Rape_analysis2018-2022\\NCRB-2021_rape victim.csv')
rape_victim_2022=pd.read_csv(r'Rape_analysis2018-2022\\2022-state wise case.csv')

In [6]:
rape_victim_2018.shape

(40, 15)

In [7]:
rape_victim_2018.head(5)

,S. No (Col.1),Category (Col.2),State/UT (Col.3),Cases Reported (Col.4),Child Victims of Rape (Below 18 Yrs) - Below 6 Years (Col.5),Child Victims of Rape (Below 18 Yrs) - 6 Years & Above - Below 12 Years (Col.6),Child Victims of Rape (Below 18 Yrs) - 12 Years & Above - Below 16 Years (Col.7),Child Victims of Rape (Below 18 Yrs) - 16 Years & Above - Below 18 Years (Col.8),Child Victims of Rape (Below 18 Yrs) - Total Girl/Child Victims (Col.9),Women Victims of Rape (Above 18 Yrs) - 18 Years & Above - Below 30 Years (Col.10),Women Victims of Rape (Above 18 Yrs) - 30 Years & Above - Below 45 Years (Col.11),Women Victims of Rape (Above 18 Yrs) - 45 Years & Above - Below 60 Years (Col.12),Women Victims of Rape (Above 18 Yrs) - 60 Years & Above (Col.13),Women Victims of Rape (Above 18 Yrs) - Total Women/Adult Victims (Col.14),Total Victims (Col.15=Col.9+ Col.14)
0,1,State,Andhra Pradesh,971.0,16.0,57.0,181.0,251.0,505.0,373.0,76,14.0,5.0,468.0,973
1,2,State,Arunachal Pradesh,67.0,4.0,4.0,13.0,11.0,32.0,29.0,9,0.0,0.0,38.0,70
2,3,State,Assam,1648.0,7.0,24.0,6.0,52.0,89.0,1043.0,523,107.0,5.0,1678.0,1767
3,4,State,Bihar,651.0,0.0,0.0,1.0,3.0,4.0,520.0,111,16.0,0.0,647.0,651
4,5,State,Chhattisgarh,2091.0,41.0,80.0,557.0,541.0,1219.0,644.0,190,42.0,6.0,882.0,2101

In [8]:
rape_victim_2018.columns

Index(['S. No (Col.1)', 'Category (Col.2)', 'State/UT (Col.3)',
       'Cases Reported (Col.4)',
       'Child Victims of Rape (Below 18 Yrs) - Below 6 Years (Col.5)',
       'Child Victims of Rape (Below 18 Yrs) - 6 Years & Above - Below 12 Years (Col.6)',
       'Child Victims of Rape (Below 18 Yrs) - 12 Years & Above - Below 16 Years (Col.7)',
       'Child Victims of Rape (Below 18 Yrs) - 16 Years & Above - Below 18 Years (Col.8)',
       'Child Victims of Rape (Below 18 Yrs) - Total Girl/Child Victims (Col.9)',
       'Women Victims of Rape (Above 18 Yrs) - 18 Years & Above - Below 30 Years (Col.10)',
       'Women Victims of Rape (Above 18 Yrs) - 30 Years & Above - Below 45 Years (Col.11)',
       'Women Victims of Rape (Above 18 Yrs) - 45 Years & Above - Below 60 Years (Col.12)',
       'Women Victims of Rape (Above 18 Yrs) - 60 Years & Above (Col.13)',
       'Women Victims of Rape (Above 18 Yrs) - Total Women/Adult Victims (Col.14)',
       'Total Victims (Col.15=Col.9+ Col.14)'],
      dtype='object')

In [9]:
rape_victim_2019.shape

(40, 14)

In [11]:
rape_victim_2019.columns

Index(['Category', 'State/UT ', 'Cases Reported ',
       'Child Victims of Rape (Below 18 Yrs) - Below 6 Years',
       'Child Victims of Rape (Below 18 Yrs) - 6 Years & Above-Below 12 Years',
       'Child Victims of Rape (Below 18 Yrs) - 12 Years & Above-Below 16 Years',
       'Child Victims of Rape (Below 18 Yrs) - 16 Years & Above-Below 18 Years',
       'Child Victims of Rape (Below 18 Yrs) - Total Girls /Child Victims',
       'Women Victims of Rape (Above 18 Yrs) - 18 Years & Abov-Below 30 Years',
       'Women Victims of Rape (Above 18 Yrs) - 30 Years & Above-Below 45 Years',
       'Women Victims of Rape (Above 18 Yrs) - 45 Years & Above-Below 60 Years',
       'Women Victims of Rape (Above 18 Yrs) - 60 Years & Above',
       'Women Victims of Rape (Above 18 Yrs) - Total Women / Adult Victims',
       'Total Victims'],
      dtype='object')

In [12]:
rape_victim_2019.head(3)

,Category,State/UT,Cases Reported,Child Victims of Rape (Below 18 Yrs) - Below 6 Years,Child Victims of Rape (Below 18 Yrs) - 6 Years & Above-Below 12 Years,Child Victims of Rape (Below 18 Yrs) - 12 Years & Above-Below 16 Years,Child Victims of Rape (Below 18 Yrs) - 16 Years & Above-Below 18 Years,Child Victims of Rape (Below 18 Yrs) - Total Girls /Child Victims,Women Victims of Rape (Above 18 Yrs) - 18 Years & Abov-Below 30 Years,Women Victims of Rape (Above 18 Yrs) - 30 Years & Above-Below 45 Years,Women Victims of Rape (Above 18 Yrs) - 45 Years & Above-Below 60 Years,Women Victims of Rape (Above 18 Yrs) - 60 Years & Above,Women Victims of Rape (Above 18 Yrs) - Total Women / Adult Victims,Total Victims
0,State,Andhra Pradesh,1086.0,16.0,38.0,184.0,323.0,561.0,431.0,89.0,21.0,2.0,543.0,1104
1,State,Arunachal Pradesh,63.0,1.0,2.0,13.0,9.0,25.0,26.0,12.0,1.0,0.0,39.0,64
2,State,Assam,1773.0,0.0,7.0,50.0,31.0,88.0,1231.0,376.0,96.0,0.0,1703.0,1791

In [13]:
rape_victim_2020.head(2)

,Si. No (Col. 1),Category,State/UT (Col. 2),Cases Reported - (Col. 3),Child Victims of Rape (Below 18 Yrs) - Below 6 Years - (Col. 4),Child Victims of Rape (Below 18 Yrs) - 6 Years & Above - Below 12 Years - (Col. 5),Child Victims of Rape (Below 18 Yrs) - 12 Years & Above - Below 16 Years - (Col. 6),Child Victims of Rape (Below 18 Yrs) - 16 Years & Above - Below 18 Years - (Col. 7),Child Victims of Rape (Below 18 Yrs) - Total Girl / Child Victims - (Col. 8),Women Victims of Rape (Above 18 Years) - 18 Years & Above - Below 30 Years - (Col. 9),Women Victims of Rape (Above 18 Years) - 30 Years & Above - Below 45 Years - (Col. 10),Women Victims of Rape (Above 18 Years) - 45 Years & Above - Below 60 Years - (Col. 11),Women Victims of Rape (Above 18 Years) - 60 Years & Above - (Col. 12),Women Victims of Rape (Above 18 Years) - Total Women / Adult Victims - (Col. 13),Total Victims (Col.8+Col.13) - (Col. 14)
0,1,State,Andhra Pradesh,1095.0,27.0,74.0,214.0,272.0,587.0,411,87.0,20.0,2.0,520.0,1107
1,2,State,Arunachal Pradesh,60.0,1.0,6.0,14.0,8.0,29.0,20,14.0,0.0,0.0,34.0,63

In [16]:
rape_victim_2020.columns

Index(['Si. No (Col. 1)', 'Category ', 'State/UT (Col. 2)',
       'Cases Reported - (Col. 3)',
       'Child Victims of Rape (Below 18 Yrs) - Below 6 Years - (Col. 4)',
       'Child Victims of Rape (Below 18 Yrs) - 6 Years & Above - Below 12 Years - (Col. 5)',
       'Child Victims of Rape (Below 18 Yrs) - 12 Years & Above - Below 16 Years - (Col. 6)',
       'Child Victims of Rape (Below 18 Yrs) - 16 Years & Above - Below 18 Years - (Col. 7)',
       'Child Victims of Rape (Below 18 Yrs) - Total Girl / Child Victims - (Col. 8)',
       'Women Victims of Rape (Above 18 Years) - 18 Years & Above - Below 30 Years - (Col. 9)',
       'Women Victims of Rape (Above 18 Years) - 30 Years & Above - Below 45 Years - (Col. 10)',
       'Women Victims of Rape (Above 18 Years) - 45 Years & Above - Below 60 Years - (Col. 11)',
       'Women Victims of Rape (Above 18 Years) - 60 Years & Above - (Col. 12)',
       'Women Victims of Rape (Above 18 Years) - Total Women / Adult Victims - (Col. 13)',
       'Total Victims (Col.8+Col.13) - (Col. 14)'],
      dtype='object')

In [14]:
rape_victim_2020.shape

(40, 15)

In [17]:
rape_victim_2021.shape

(40, 14)

In [18]:
rape_victim_2021.columns

Index(['Sl. No. Col. (1)', 'State/UT Col. (2)', 'Cases Reported Col. (3)',
       'Child Victims of Rape (Below 18 Yrs) - Below 6 Years - Col. (4)',
       'Child Victims of Rape (Below 18 Yrs) - 6 Years & Above - Below 12 Years - Col. (5)',
       'Child Victims of Rape (Below 18 Yrs) - 12 Years & Above - Below 16 Years - Col. (6)',
       'Child Victims of Rape (Below 18 Yrs) - 16 Years & Above - Below 18 Years - Col. (7)',
       'Child Victims of Rape (Below 18 Yrs) - Total Girl / Child Victims - Col. (8)',
       'Women Victims of Rape (Above 18 Years) - 18 Years & Above - Below 30 Years - Col. (9)',
       'Women Victims of Rape (Above 18 Years) - 30 Years & Above - Below 45 Years - Col. (10)',
       'Women Victims of Rape (Above 18 Years) - 45 Years & Above - Below 60 Years - Col. (11)',
       'Women Victims of Rape (Above 18 Years) - 60 Years & Above - Col. (12)',
       'Women Victims of Rape (Above 18 Years) - Total Women / Adult Victims - Col. (13)',
       'Total Victims (Col.8+Col.13) - Col. (14)'],
      dtype='object')

In [19]:
rape_victim_2022.shape

(40, 14)

In [20]:
rape_victim_2022.columns

Index(['Sl. No.', 'State/UT', 'Cases Reported - Col.(3)',
       'Child Victims of Rape (Below 18 Yrs) - Below 6 Years - Col.(4)',
       'Child Victims of Rape (Below 18 Yrs) - 6 Years and Above - Below 12 Years - Col.(5)',
       'Child Victims of Rape (Below 18 Yrs) - 12 Years and Above - Below 16 Years - Col.(6)',
       'Child Victims of Rape (Below 18 Yrs) - 16 Years and Above - Below 18 Years - Col.(7)',
       'Child Victims of Rape (Below 18 Yrs) - Total Girl / Child Victims - Col.(8)',
       'Women Victims of Rape (Above 18 Years) - 18 Years and Above - Below 30 Years - Col.(9)',
       'Women Victims of Rape (Above 18 Years) - 30 Years and Above - Below 45 Years - Col.(10)',
       'Women Victims of Rape (Above 18 Years) - 45 Years and Above - Below 60 Years - Col.(11)',
       'Women Victims of Rape (Above 18 Years) - 60 Years and Above - Col.(12)',
       'Women Victims of Rape (Above 18 Years) - Total Women / Adult Victims - Col.(13)',
       'Total Victims (Col.8+Col.13) - Col.(14)'],
      dtype='object')

Kidnapping dataset

In [23]:
kidnapping_2018_2020=pd.read_csv(r'Kidnapping_2018_2022\NCRB2018-2020.csv')

In [24]:
kidnapping_Data2019_2021=pd.read_csv(r'Kidnapping_2018_2022\NCRb kidnapping 2019-2021.csv')

In [25]:
kidnapping_2020_2022=pd.read_csv(r'Kidnapping_2018_2022\kidnapping2021.csv')

In [31]:
kidnapping_2018_2020.head(1)

,SI. No.,City,2018,2019,2020,Actual Population (in Lakhs) (2011),Rate of Kidnapping & Abduction (2020),Chargesheeting Rate (2020)
0,1,Ahmedabad (Gujarat),277,248,181,63.5,2.8,22.3

In [30]:
kidnapping_Data2019_2021.head(1)

,Sl. No.,State/UT,2019,2020,2021,Mid-Year Projected Population (in Lakhs) (2021),Rate of Kidnapping & Abduction (2021),Chargesheeting Rate (2021)
0,1,Andhra Pradesh,902.0,737,835,528.5,1.6,71.8

In [29]:
kidnapping_2020_2022.head(1)

,Sl. No.,State/UT,2020,2021,2022,Mid-Year Projected Population (in Lakhs) (2022),Rate of Kidnapping and Abduction (2022),Chargesheeting Rate (2022)
0,1,Andhra Pradesh,737,835,903,530.3,1.7,62.4

Population data

In [32]:
population=pd.read_csv('population.csv')

In [33]:
population.head(2)

           State  Population
0  Uttar Pradesh   199812341
1    Maharashtra   112374333

In [34]:
population.shape

(30, 2)