# Data Preprocessing

In [1183]:
import pandas as pd

## 1. Rape Data Preprocessing

In [1184]:
rape_victim_2018= pd.read_csv(r'Rape_analysis2018-2022\\NCRB_CII_2018_rape_victim.csv')
rape_victim_2019=pd.read_csv(r'Rape_analysis2018-2022\\NCRB_CII-2019_rape victim.csv')
rape_victim_2020= pd.read_csv(r'Rape_analysis2018-2022\\NCRB_2020_rape victim.csv')
rape_victim_2021=pd.read_csv(r'Rape_analysis2018-2022\\NCRB-2021_rape victim.csv')
rape_victim_2022=pd.read_csv(r'Rape_analysis2018-2022\\2022-state wise case.csv')

- Year: 2018

In [1185]:
rape_victim_2018.columns

Index(['S. No (Col.1)', 'Category (Col.2)', 'State/UT (Col.3)',
       'Cases Reported (Col.4)',
       'Child Victims of Rape (Below 18 Yrs) - Below 6 Years (Col.5)',
       'Child Victims of Rape (Below 18 Yrs) - 6 Years & Above - Below 12 Years (Col.6)',
       'Child Victims of Rape (Below 18 Yrs) - 12 Years & Above - Below 16 Years (Col.7)',
       'Child Victims of Rape (Below 18 Yrs) - 16 Years & Above - Below 18 Years (Col.8)',
       'Child Victims of Rape (Below 18 Yrs) - Total Girl/Child Victims (Col.9)',
       'Women Victims of Rape (Above 18 Yrs) - 18 Years & Above - Below 30 Years (Col.10)',
       'Women Victims of Rape (Above 18 Yrs) - 30 Years & Above - Below 45 Years (Col.11)',
       'Women Victims of Rape (Above 18 Yrs) - 45 Years & Above - Below 60 Years (Col.12)',
       'Women Victims of Rape (Above 18 Yrs) - 60 Years & Above (Col.13)',
       'Women Victims of Rape (Above 18 Yrs) - Total Women/Adult Victims (Col.14)',
       'Total Victims (Col.15=Col.9+ Col.14)'],
      dtype='object')

In [1186]:
rape_victim_2018.head(5)

,S. No (Col.1),Category (Col.2),State/UT (Col.3),Cases Reported (Col.4),Child Victims of Rape (Below 18 Yrs) - Below 6 Years (Col.5),Child Victims of Rape (Below 18 Yrs) - 6 Years & Above - Below 12 Years (Col.6),Child Victims of Rape (Below 18 Yrs) - 12 Years & Above - Below 16 Years (Col.7),Child Victims of Rape (Below 18 Yrs) - 16 Years & Above - Below 18 Years (Col.8),Child Victims of Rape (Below 18 Yrs) - Total Girl/Child Victims (Col.9),Women Victims of Rape (Above 18 Yrs) - 18 Years & Above - Below 30 Years (Col.10),Women Victims of Rape (Above 18 Yrs) - 30 Years & Above - Below 45 Years (Col.11),Women Victims of Rape (Above 18 Yrs) - 45 Years & Above - Below 60 Years (Col.12),Women Victims of Rape (Above 18 Yrs) - 60 Years & Above (Col.13),Women Victims of Rape (Above 18 Yrs) - Total Women/Adult Victims (Col.14),Total Victims (Col.15=Col.9+ Col.14)
0,1,State,Andhra Pradesh,971.0,16.0,57.0,181.0,251.0,505.0,373.0,76,14.0,5.0,468.0,973
1,2,State,Arunachal Pradesh,67.0,4.0,4.0,13.0,11.0,32.0,29.0,9,0.0,0.0,38.0,70
2,3,State,Assam,1648.0,7.0,24.0,6.0,52.0,89.0,1043.0,523,107.0,5.0,1678.0,1767
3,4,State,Bihar,651.0,0.0,0.0,1.0,3.0,4.0,520.0,111,16.0,0.0,647.0,651
4,5,State,Chhattisgarh,2091.0,41.0,80.0,557.0,541.0,1219.0,644.0,190,42.0,6.0,882.0,2101

1. Column selection

In [1187]:
# for state risk just need- category,state/ut,year,cases
rape_victim_2018_risk=rape_victim_2018[['State/UT (Col.3)','Cases Reported (Col.4)']]

Add column - "Year"

In [1188]:
rape_victim_2018_risk = rape_victim_2018_risk.copy()
rape_victim_2018_risk['Year'] = 2018
rape_victim_2018_risk

                            State/UT (Col.3)  Cases Reported (Col.4)  Year
0                             Andhra Pradesh                   971.0  2018
1                          Arunachal Pradesh                    67.0  2018
2                                      Assam                  1648.0  2018
3                                      Bihar                   651.0  2018
4                               Chhattisgarh                  2091.0  2018
5                                        Goa                    61.0  2018
6                                    Gujarat                   553.0  2018
7                                    Haryana                  1296.0  2018
8                           Himachal Pradesh                   344.0  2018
9                            Jammu & Kashmir                   320.0  2018
10                                 Jharkhand                  1090.0  2018
11                                 Karnataka                   492.0  2018
12                                    Kerala                  1945.0  2018
13                            Madhya Pradesh                  5433.0  2018
14                               Maharashtra                  2142.0  2018
15                                   Manipur                    52.0  2018
16                                 Meghalaya                    87.0  2018
17                                   Mizoram                    50.0  2018
18                                  Nagaland                    10.0  2018
19                                    Odisha                   918.0  2018
20                                    Punjab                   831.0  2018
21                                 Rajasthan                  4335.0  2018
22                                    Sikkim                    16.0  2018
23                                Tamil Nadu                   331.0  2018
24                                 Telangana                   606.0  2018
25                                   Tripura                    97.0  2018
26                             Uttar Pradesh                  3946.0  2018
27                               Uttarakhand                   561.0  2018
28                               West Bengal                  1069.0  2018
29                            Total State(s)                 32013.0  2018
30                             A & N Islands                    30.0  2018
31                                Chandigarh                    86.0  2018
32                                D&N Haveli                     7.0  2018
33                               Daman & Diu                     3.0  2018
34                                  Delhi UT                  1215.0  2018
35                               Lakshadweep                     2.0  2018
36                                Puducherry                     0.0  2018
37                               Total UT(s)                  1343.0  2018
38                         Total (All India)                 33356.0  2018
39  Percentage Share of Age-Group of Victims                     NaN  2018

Rename column

In [1189]:
# rename column  - give them proper name
rape_victim_2018_risk = rape_victim_2018_risk.rename(columns={
    'State/UT (Col.3)': 'State/UT',
    'Cases Reported (Col.4)': 'Cases'
})
rape_victim_2018_risk

                                    State/UT    Cases  Year
0                             Andhra Pradesh    971.0  2018
1                          Arunachal Pradesh     67.0  2018
2                                      Assam   1648.0  2018
3                                      Bihar    651.0  2018
4                               Chhattisgarh   2091.0  2018
5                                        Goa     61.0  2018
6                                    Gujarat    553.0  2018
7                                    Haryana   1296.0  2018
8                           Himachal Pradesh    344.0  2018
9                            Jammu & Kashmir    320.0  2018
10                                 Jharkhand   1090.0  2018
11                                 Karnataka    492.0  2018
12                                    Kerala   1945.0  2018
13                            Madhya Pradesh   5433.0  2018
14                               Maharashtra   2142.0  2018
15                                   Manipur     52.0  2018
16                                 Meghalaya     87.0  2018
17                                   Mizoram     50.0  2018
18                                  Nagaland     10.0  2018
19                                    Odisha    918.0  2018
20                                    Punjab    831.0  2018
21                                 Rajasthan   4335.0  2018
22                                    Sikkim     16.0  2018
23                                Tamil Nadu    331.0  2018
24                                 Telangana    606.0  2018
25                                   Tripura     97.0  2018
26                             Uttar Pradesh   3946.0  2018
27                               Uttarakhand    561.0  2018
28                               West Bengal   1069.0  2018
29                            Total State(s)  32013.0  2018
30                             A & N Islands     30.0  2018
31                                Chandigarh     86.0  2018
32                                D&N Haveli      7.0  2018
33                               Daman & Diu      3.0  2018
34                                  Delhi UT   1215.0  2018
35                               Lakshadweep      2.0  2018
36                                Puducherry      0.0  2018
37                               Total UT(s)   1343.0  2018
38                         Total (All India)  33356.0  2018
39  Percentage Share of Age-Group of Victims      NaN  2018

remove unneccesarry data

In [1190]:
# not neccesary last 3 records
rape_victim_2018_risk=rape_victim_2018_risk.loc[rape_victim_2018_risk.index[:-3]]

- Year : 2019

In [1191]:
# inspect data - 2019
rape_victim_2019.head(3)

,Category,State/UT,Cases Reported,Child Victims of Rape (Below 18 Yrs) - Below 6 Years,Child Victims of Rape (Below 18 Yrs) - 6 Years & Above-Below 12 Years,Child Victims of Rape (Below 18 Yrs) - 12 Years & Above-Below 16 Years,Child Victims of Rape (Below 18 Yrs) - 16 Years & Above-Below 18 Years,Child Victims of Rape (Below 18 Yrs) - Total Girls /Child Victims,Women Victims of Rape (Above 18 Yrs) - 18 Years & Abov-Below 30 Years,Women Victims of Rape (Above 18 Yrs) - 30 Years & Above-Below 45 Years,Women Victims of Rape (Above 18 Yrs) - 45 Years & Above-Below 60 Years,Women Victims of Rape (Above 18 Yrs) - 60 Years & Above,Women Victims of Rape (Above 18 Yrs) - Total Women / Adult Victims,Total Victims
0,State,Andhra Pradesh,1086.0,16.0,38.0,184.0,323.0,561.0,431.0,89.0,21.0,2.0,543.0,1104
1,State,Arunachal Pradesh,63.0,1.0,2.0,13.0,9.0,25.0,26.0,12.0,1.0,0.0,39.0,64
2,State,Assam,1773.0,0.0,7.0,50.0,31.0,88.0,1231.0,376.0,96.0,0.0,1703.0,1791

- Feature Selection

In [1192]:
# filter data 
rape_victim_2019_risk=rape_victim_2019[['State/UT ', 'Cases Reported ']]

- (Feature Creation) Add column "year"

In [1193]:
# add year
rape_victim_2019_risk=rape_victim_2019_risk.copy()
rape_victim_2019_risk['Year'] = 2019

Rename column

In [1194]:
rape_victim_2019_risk = rape_victim_2019_risk.rename(columns={
    'State/UT ':'State/UT',
    'Cases Reported ': 'Cases'
})

remove unneccesarry data

In [1195]:
rape_victim_2019_risk=rape_victim_2019_risk.iloc[rape_victim_2019_risk.index[:-3]]

Year : 2020

In [1196]:
rape_victim_2020.head(3)

,Si. No (Col. 1),Category,State/UT (Col. 2),Cases Reported - (Col. 3),Child Victims of Rape (Below 18 Yrs) - Below 6 Years - (Col. 4),Child Victims of Rape (Below 18 Yrs) - 6 Years & Above - Below 12 Years - (Col. 5),Child Victims of Rape (Below 18 Yrs) - 12 Years & Above - Below 16 Years - (Col. 6),Child Victims of Rape (Below 18 Yrs) - 16 Years & Above - Below 18 Years - (Col. 7),Child Victims of Rape (Below 18 Yrs) - Total Girl / Child Victims - (Col. 8),Women Victims of Rape (Above 18 Years) - 18 Years & Above - Below 30 Years - (Col. 9),Women Victims of Rape (Above 18 Years) - 30 Years & Above - Below 45 Years - (Col. 10),Women Victims of Rape (Above 18 Years) - 45 Years & Above - Below 60 Years - (Col. 11),Women Victims of Rape (Above 18 Years) - 60 Years & Above - (Col. 12),Women Victims of Rape (Above 18 Years) - Total Women / Adult Victims - (Col. 13),Total Victims (Col.8+Col.13) - (Col. 14)
0,1,State,Andhra Pradesh,1095.0,27.0,74.0,214.0,272.0,587.0,411,87.0,20.0,2.0,520.0,1107
1,2,State,Arunachal Pradesh,60.0,1.0,6.0,14.0,8.0,29.0,20,14.0,0.0,0.0,34.0,63
2,3,State,Assam,1657.0,0.0,0.0,6.0,12.0,18.0,1006,584.0,50.0,0.0,1640.0,1658

- Feature selection

In [1197]:
rape_victim_2020_risk=rape_victim_2020[['State/UT (Col. 2)',
       'Cases Reported - (Col. 3)']]

Add 'Year' column

In [1198]:
rape_victim_2020_risk=rape_victim_2020_risk.copy()
rape_victim_2020_risk['Year']=2020

rename column name

In [1199]:
#rename
rape_victim_2020_risk=rape_victim_2020_risk.rename(columns={
    'State/UT (Col. 2)':'State/UT',
    'Cases Reported - (Col. 3)':'Cases'
})

remove unneccesarry data

In [1200]:
rape_victim_2020_risk=rape_victim_2020_risk.iloc[rape_victim_2020_risk.index[:-3]]

##### year : 2021

In [1201]:
rape_victim_2021.head(3)

,Sl. No. Col. (1),State/UT Col. (2),Cases Reported Col. (3),Child Victims of Rape (Below 18 Yrs) - Below 6 Years - Col. (4),Child Victims of Rape (Below 18 Yrs) - 6 Years & Above - Below 12 Years - Col. (5),Child Victims of Rape (Below 18 Yrs) - 12 Years & Above - Below 16 Years - Col. (6),Child Victims of Rape (Below 18 Yrs) - 16 Years & Above - Below 18 Years - Col. (7),Child Victims of Rape (Below 18 Yrs) - Total Girl / Child Victims - Col. (8),Women Victims of Rape (Above 18 Years) - 18 Years & Above - Below 30 Years - Col. (9),Women Victims of Rape (Above 18 Years) - 30 Years & Above - Below 45 Years - Col. (10),Women Victims of Rape (Above 18 Years) - 45 Years & Above - Below 60 Years - Col. (11),Women Victims of Rape (Above 18 Years) - 60 Years & Above - Col. (12),Women Victims of Rape (Above 18 Years) - Total Women / Adult Victims - Col. (13),Total Victims (Col.8+Col.13) - Col. (14)
0,1,Andhra Pradesh,1188.0,17.0,50.0,259.0,288.0,614.0,463.0,108.0,14.0,5.0,590.0,1204.0
1,2,Arunachal Pradesh,83.0,1.0,3.0,15.0,35.0,54.0,13.0,5.0,11.0,0.0,29.0,83.0
2,3,Assam,1733.0,0.0,1.0,2.0,0.0,3.0,1306.0,470.0,56.0,0.0,1832.0,1835.0

Feature (column) Selection

In [1202]:
rape_victim_2021_risk=rape_victim_2021[['State/UT Col. (2)', 'Cases Reported Col. (3)']]

Add 'Year' column

In [1203]:
rape_victim_2021_risk=rape_victim_2021_risk.copy()
rape_victim_2021_risk['Year']=2021

Rename column name

In [1204]:
rape_victim_2021_risk=rape_victim_2021_risk.rename(columns={
    'State/UT Col. (2)':'State/UT',
    'Cases Reported Col. (3)':'Cases'
})

remove unneccesarry data

In [1205]:
rape_victim_2021_risk=rape_victim_2021_risk.iloc[rape_victim_2021_risk.index[:-3]]

##### year : 2022

In [1206]:
rape_victim_2022.head(3)

,Sl. No.,State/UT,Cases Reported - Col.(3),Child Victims of Rape (Below 18 Yrs) - Below 6 Years - Col.(4),Child Victims of Rape (Below 18 Yrs) - 6 Years and Above - Below 12 Years - Col.(5),Child Victims of Rape (Below 18 Yrs) - 12 Years and Above - Below 16 Years - Col.(6),Child Victims of Rape (Below 18 Yrs) - 16 Years and Above - Below 18 Years - Col.(7),Child Victims of Rape (Below 18 Yrs) - Total Girl / Child Victims - Col.(8),Women Victims of Rape (Above 18 Years) - 18 Years and Above - Below 30 Years - Col.(9),Women Victims of Rape (Above 18 Years) - 30 Years and Above - Below 45 Years - Col.(10),Women Victims of Rape (Above 18 Years) - 45 Years and Above - Below 60 Years - Col.(11),Women Victims of Rape (Above 18 Years) - 60 Years and Above - Col.(12),Women Victims of Rape (Above 18 Years) - Total Women / Adult Victims - Col.(13),Total Victims (Col.8+Col.13) - Col.(14)
0,1,Andhra Pradesh,621.0,0.0,0.0,0.0,0.0,0.0,458.0,160,8.0,1.0,627.0,627
1,2,Arunachal Pradesh,74.0,1.0,3.0,17.0,9.0,30.0,24.0,19,1.0,0.0,44.0,74
2,3,Assam,1113.0,0.0,0.0,2.0,2.0,4.0,868.0,455,151.0,0.0,1474.0,1478

select required Column/feature

In [1207]:
rape_victim_2022_risk=rape_victim_2022[['State/UT', 'Cases Reported - Col.(3)']]

Add 'year'

In [1208]:
rape_victim_2022_risk=rape_victim_2022_risk.copy()
rape_victim_2022_risk['Year']=2022

rename column name

In [1209]:
rape_victim_2022_risk=rape_victim_2022_risk.rename(columns={
    'State/UT':'State/UT',
    'Cases Reported - Col.(3)':'Cases'
})

remove Unneccesarry data row

In [1210]:
rape_victim_2022_risk=rape_victim_2022_risk.iloc[rape_victim_2022_risk.index[:-3]]

In [1211]:
print(rape_victim_2018_risk.columns)
print(rape_victim_2019_risk.columns)
print(rape_victim_2020_risk.columns)
print(rape_victim_2021_risk.columns)
print(rape_victim_2022_risk.columns)

Index(['State/UT', 'Cases', 'Year'], dtype='object')
Index(['State/UT', 'Cases', 'Year'], dtype='object')
Index(['State/UT', 'Cases', 'Year'], dtype='object')
Index(['State/UT', 'Cases', 'Year'], dtype='object')
Index(['State/UT', 'Cases', 'Year'], dtype='object')

##### Merge Data of 5 years

In [1212]:
Data_rape=pd.concat((rape_victim_2018_risk,rape_victim_2019_risk,rape_victim_2020_risk,rape_victim_2021_risk,rape_victim_2022_risk))

In [1213]:
Data_rape

             State/UT   Cases  Year
0      Andhra Pradesh   971.0  2018
1   Arunachal Pradesh    67.0  2018
2               Assam  1648.0  2018
3               Bihar   651.0  2018
4        Chhattisgarh  2091.0  2018
..                ...     ...   ...
32              Delhi  1212.0  2022
33  Jammu and Kashmir   287.0  2022
34             Ladakh     5.0  2022
35        Lakshadweep     4.0  2022
36         Puducherry     9.0  2022

[185 rows x 3 columns]

### Standardize State Names

In [1214]:
Data_rape.groupby('Year')['State/UT'].nunique()

Year
2018    37
2019    37
2020    37
2021    37
2022    37
Name: State/UT, dtype: int64

Total states : 28 ,
Total UT's : 8              
Total States/UT's : 36

In [1215]:
Data_rape['State/UT'].unique()

array(['Andhra Pradesh', 'Arunachal Pradesh', 'Assam', 'Bihar',
       'Chhattisgarh', 'Goa', 'Gujarat', 'Haryana', 'Himachal Pradesh',
       'Jammu & Kashmir', 'Jharkhand', 'Karnataka', 'Kerala',
       'Madhya Pradesh', 'Maharashtra', 'Manipur', 'Meghalaya', 'Mizoram',
       'Nagaland', 'Odisha', 'Punjab', 'Rajasthan', 'Sikkim',
       'Tamil Nadu', 'Telangana', 'Tripura', 'Uttar Pradesh',
       'Uttarakhand', 'West Bengal', 'Total State(s)', 'A & N Islands',
       'Chandigarh', 'D&N Haveli', 'Daman & Diu', 'Delhi UT',
       'Lakshadweep', 'Puducherry', 'Andhra Pradesh ', 'Assam ', 'Bihar ',
       'Chhattisgarh ', 'Goa ', 'Gujarat ', 'Haryana ', 'Jharkhand ',
       'Karnataka ', 'Kerala ', 'Maharashtra ', 'Manipur ', 'Meghalaya* ',
       'Mizoram ', 'Nagaland ', 'Odisha ', 'Punjab ', 'Rajasthan ',
       'Sikkim ', 'Tamil Nadu ', 'Telangana ', 'Tripura ', 'Uttarakhand ',
       'West Bengal ', 'TOTAL STATE(S)', 'Chandigarh ', 'D & N Haveli ',
       'Daman & Diu ', 'Delhi UT ', 'Lakshadweep ', 'Puducherry ',
       'D & N Haveli and Daman & Diu', 'Delhi', 'Ladakh',
       'Total State (S)', 'Andaman and Nicobar Islands',
       'Dadra and Nagar Haveli and Daman and Diu', 'Jammu and Kashmir'],
      dtype=object)

1. Inconsistent State Name : Same state name but diffrently written with extra spaces
'Andhra Pradesh' , 'Andhra Pradesh '              
'Assam' , 'Assam '            
'Bihar' , 'Bihar '.....

2. Inconsistent : 'and' and '&'

In [1216]:
# trim space nd ... 
Data_rape['State/UT'] = Data_rape['State/UT'].str.strip()

In [1217]:
Data_rape['State/UT'] = Data_rape['State/UT'].str.replace('&', 'and')

In [1218]:
Data_rape['State/UT'] = Data_rape['State/UT'].str.title()

3. Improper State/UT names

In [1219]:
Data_rape['State/UT'] = Data_rape['State/UT'].replace( 
    {
    'A And N Islands': 'Andaman And Nicobar Islands',
    'Delhi Ut': 'Delhi',
    'D And N Haveli': 'Dadra And Nagar Haveli And Daman And Diu',
    'Dandn Haveli': 'Dadra And Nagar Haveli And Daman And Diu',
    'Dadra And Nagar Haveli': 'Dadra And Nagar Haveli And Daman And Diu',
    'Daman And Diu': 'Dadra And Nagar Haveli And Daman And Diu',
    'D And N Haveli And Daman And Diu': 'Dadra And Nagar Haveli And Daman And Diu'
} )

In [1220]:
Data_rape['State/UT'].unique()

array(['Andhra Pradesh', 'Arunachal Pradesh', 'Assam', 'Bihar',
       'Chhattisgarh', 'Goa', 'Gujarat', 'Haryana', 'Himachal Pradesh',
       'Jammu And Kashmir', 'Jharkhand', 'Karnataka', 'Kerala',
       'Madhya Pradesh', 'Maharashtra', 'Manipur', 'Meghalaya', 'Mizoram',
       'Nagaland', 'Odisha', 'Punjab', 'Rajasthan', 'Sikkim',
       'Tamil Nadu', 'Telangana', 'Tripura', 'Uttar Pradesh',
       'Uttarakhand', 'West Bengal', 'Total State(S)',
       'Andaman And Nicobar Islands', 'Chandigarh',
       'Dadra And Nagar Haveli And Daman And Diu', 'Delhi', 'Lakshadweep',
       'Puducherry', 'Meghalaya*', 'Ladakh', 'Total State (S)'],
      dtype=object)

4. Founded 2 Invalid state names : 'Total State (S)' and 'Total State(S)'

In [1221]:
Data_rape = Data_rape[~Data_rape['State/UT'].str.contains('Total', case=False)]

5. Meghalaya and meghalaya* both are diffrent

In [1222]:
Data_rape['State/UT'] = Data_rape['State/UT'].replace({
    'Meghalaya*':'Meghalaya'
})

C:\Users\dell\AppData\Local\Temp\ipykernel_5684\2061089341.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Data_rape['State/UT'] = Data_rape['State/UT'].replace({

- Is data complete? : All States/UT names present?

In [1223]:
Data_rape.groupby('Year')['State/UT'].nunique()

Year
2018    35
2019    35
2020    36
2021    36
2022    36
Name: State/UT, dtype: int64

- Missing 1 state/UT in 2018 and 2019

In [1224]:
Data_rape['State/UT'].unique()

array(['Andhra Pradesh', 'Arunachal Pradesh', 'Assam', 'Bihar',
       'Chhattisgarh', 'Goa', 'Gujarat', 'Haryana', 'Himachal Pradesh',
       'Jammu And Kashmir', 'Jharkhand', 'Karnataka', 'Kerala',
       'Madhya Pradesh', 'Maharashtra', 'Manipur', 'Meghalaya', 'Mizoram',
       'Nagaland', 'Odisha', 'Punjab', 'Rajasthan', 'Sikkim',
       'Tamil Nadu', 'Telangana', 'Tripura', 'Uttar Pradesh',
       'Uttarakhand', 'West Bengal', 'Andaman And Nicobar Islands',
       'Chandigarh', 'Dadra And Nagar Haveli And Daman And Diu', 'Delhi',
       'Lakshadweep', 'Puducherry', 'Ladakh'], dtype=object)

- Which State/UT is missing in 2018 and 2019?

In [1225]:
# which state/UT is not present in 2018-19 which is present in 2020-22
states_2018 = set(Data_rape[Data_rape['Year']==2018]['State/UT'])
states_2022 = set(Data_rape[Data_rape['Year']==2022]['State/UT'])
missing_state = states_2022 - states_2018
missing_state

{'Ladakh'}

In [1226]:
states_2019 = set(Data_rape[Data_rape['Year']==2019]['State/UT'])
states_2022 - states_2019

{'Ladakh'}

1️⃣ Ladakh missing (Normal hai)

Ladakh

2019 se pehle Ladakh alag UT nahi tha.
Wo Jammu and Kashmir ka part tha.

Isliye:

2018 data me Ladakh nahi milega

2020 ke baad separate entry mil sakti hai

Ye dataset structure ka normal change hai, problem nahi hai.

2️⃣ Meghalaya missing in 2019

Meghalaya

Ye thoda unusual hai, but NCRB datasets me kabhi-kabhi:

data not reported

0 cases

ya table me entry missing

ho sakti hai.

Isko data limitation ke roop me mention kar sakti ho.

Example:

Meghalaya data was not present in the 2019 dataset, possibly due to reporting differences in NCRB tables.
1️⃣ New UT formation

Example:

Ladakh

2019 ke baad Jammu & Kashmir split hua tha:

Jammu and Kashmir
Ladakh

Isliye 2018–2019 dataset me Ladakh alag entry nahi hoti.

- 2018 and 2019 don't have - 'Ladakh' because of administrative change.
before 2019 ladakh and j&k is one UT

In [1227]:
Data_rape.groupby('Year')['State/UT'].nunique()

Year
2018    35
2019    35
2020    36
2021    36
2022    36
Name: State/UT, dtype: int64

- change column name 'State/UT' -> 'State'

In [1228]:
Data_rape.rename(columns={'State/UT':'State'},inplace=True)

C:\Users\dell\AppData\Local\Temp\ipykernel_5684\235703135.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Data_rape.rename(columns={'State/UT':'State'},inplace=True)

Only State data.

In [1229]:
States = pd.DataFrame({
    "State": [
        'Andhra Pradesh', 'Arunachal Pradesh', 'Assam', 'Bihar',
        'Chhattisgarh', 'Goa', 'Gujarat', 'Haryana',
        'Himachal Pradesh', 'Jharkhand', 'Karnataka', 'Kerala',
        'Madhya Pradesh', 'Maharashtra', 'Manipur', 'Meghalaya',
        'Mizoram', 'Nagaland', 'Odisha', 'Punjab',
        'Rajasthan', 'Sikkim', 'Tamil Nadu', 'Telangana',
        'Tripura', 'Uttar Pradesh', 'Uttarakhand', 'West Bengal'
    ]
})

- Merge rape data with states

In [1230]:
RapeData_2018_22_Statewise= pd.merge(States,Data_rape,on='State',how='left')

- convert case data type from float to int

In [1231]:
RapeData_2018_22_Statewise['Cases']=RapeData_2018_22_Statewise['Cases'].astype('int')

### 5 Years Rape data

In [1232]:
RapeData_2018_22_Statewise

              State  Cases  Year
0    Andhra Pradesh    971  2018
1    Andhra Pradesh   1086  2019
2    Andhra Pradesh   1095  2020
3    Andhra Pradesh   1188  2021
4    Andhra Pradesh    621  2022
..              ...    ...   ...
135     West Bengal   1069  2018
136     West Bengal   1069  2019
137     West Bengal   1128  2020
138     West Bengal   1123  2021
139     West Bengal   1111  2022

[140 rows x 3 columns]

In [1233]:
RapeData_2018_22_Statewise['Cases']=RapeData_2018_22_Statewise['Cases'].astype('int')

In [1234]:
print("Before saving:", RapeData_2018_22_Statewise.shape)
RapeData_2018_22_Statewise.to_csv("RapeData_2018_22_Statewise.csv", index=False)
df_check = pd.read_csv("RapeData_2018_22_Statewise.csv")
print("After saving:", df_check.shape)

Before saving: (140, 3)
After saving: (140, 3)

## Population Data Preprocessing

In [1235]:
## Population Data
population=pd.read_csv('population.csv')

In [1236]:
population.shape

(30, 2)

In [1237]:
population.head(5)

            State  Population
0   Uttar Pradesh   199812341
1     Maharashtra   112374333
2           Bihar   104099452
3     West Bengal    91276115
4  Madhya Pradesh    72626809

In [1238]:
population['State'].unique()

array(['Uttar Pradesh', 'Maharashtra', 'Bihar', 'West Bengal',
       'Madhya Pradesh', 'Tamil Nadu', 'Rajasthan', 'Karnataka',
       'Gujarat', 'Andhra Pradesh', 'Odisha', 'Telangana', 'Kerala',
       'Jharkhand', 'Assam', 'Punjab', 'Chhattisgarh', 'Haryana', 'Delhi',
       'Jammu and Kashmir', 'Uttarakhand', 'Himachal Pradesh', 'Tripura',
       'Meghalaya', 'Manipur', 'Nagaland', 'Goa', 'Arunachal Pradesh',
       'Mizoram', 'Sikkim'], dtype=object)

In [1239]:
population.isnull().sum()

State         0
Population    0
dtype: int64

In [1240]:
population.duplicated().sum()

0

Only state data

In [1241]:
State_population = pd.merge(States,population,on='State',how='left')

### Population of States Data

In [1242]:
State_population

                State  Population
0      Andhra Pradesh    49577103
1   Arunachal Pradesh     1383727
2               Assam    31205576
3               Bihar   104099452
4        Chhattisgarh    25545198
5                 Goa     1458545
6             Gujarat    60439692
7             Haryana    25351462
8    Himachal Pradesh     6864602
9           Jharkhand    32988134
10          Karnataka    61095297
11             Kerala    33406061
12     Madhya Pradesh    72626809
13        Maharashtra   112374333
14            Manipur     2855794
15          Meghalaya     2966889
16            Mizoram     1097206
17           Nagaland     1978502
18             Odisha    41974218
19             Punjab    27743338
20          Rajasthan    68548437
21             Sikkim      610577
22         Tamil Nadu    72147030
23          Telangana    35193978
24            Tripura     3673917
25      Uttar Pradesh   199812341
26        Uttarakhand    10086292
27        West Bengal    91276115

## Merge Population Data

In [1243]:
Rapecases5year_states_population=pd.merge(State_population,RapeData_2018_22_Statewise,on='State',how='left')

In [1244]:
Rapecases5year_states_population

              State  Population  Cases  Year
0    Andhra Pradesh    49577103    971  2018
1    Andhra Pradesh    49577103   1086  2019
2    Andhra Pradesh    49577103   1095  2020
3    Andhra Pradesh    49577103   1188  2021
4    Andhra Pradesh    49577103    621  2022
..              ...         ...    ...   ...
135     West Bengal    91276115   1069  2018
136     West Bengal    91276115   1069  2019
137     West Bengal    91276115   1128  2020
138     West Bengal    91276115   1123  2021
139     West Bengal    91276115   1111  2022

[140 rows x 4 columns]

In [1245]:
Rapecases5year_states_population.isnull().sum()

State         0
Population    0
Cases         0
Year          0
dtype: int64

rename column - case -> rapecases

In [1246]:
Rapecases5year_states_population.rename(columns=({'Cases':'Rape Cases'}),inplace=True)

## Kidnapping Data Preprocessing

In [1247]:
States = pd.DataFrame({
    "State": [
        'Andhra Pradesh', 'Arunachal Pradesh', 'Assam', 'Bihar',
        'Chhattisgarh', 'Goa', 'Gujarat', 'Haryana',
        'Himachal Pradesh', 'Jharkhand', 'Karnataka', 'Kerala',
        'Madhya Pradesh', 'Maharashtra', 'Manipur', 'Meghalaya',
        'Mizoram', 'Nagaland', 'Odisha', 'Punjab',
        'Rajasthan', 'Sikkim', 'Tamil Nadu', 'Telangana',
        'Tripura', 'Uttar Pradesh', 'Uttarakhand', 'West Bengal'
    ]
})

In [1248]:
kidnapping_2018=pd.read_csv(r'Kidnapping_2018_2022/kidnnapping_2018.csv')

In [1249]:
kidnapping_2018.head(5)

               State  Year  Kidnapping_Cases
0     Andhra Pradesh  2018              1833
1  Arunachal Pradesh  2018               180
2              Assam  2018              5869
3              Bihar  2018             11257
4       Chhattisgarh  2018              2555

In [1250]:
kidnapping_2018.shape

(36, 3)

In [1251]:
kidnapping_2018.rename(columns={'Kidnapping_Cases':'2018'},inplace=True)

In [1252]:
kidnapping_2018=kidnapping_2018[['State','2018']]

In [1253]:
kidnapping_2018['State'].unique()

array(['Andhra Pradesh', 'Arunachal Pradesh', 'Assam', 'Bihar',
       'Chhattisgarh', 'Goa', 'Gujarat', 'Haryana', 'Himachal Pradesh',
       'Jammu & Kashmir', 'Jharkhand', 'Karnataka', 'Kerala',
       'Madhya Pradesh', 'Maharashtra', 'Manipur', 'Meghalaya', 'Mizoram',
       'Nagaland', 'Odisha', 'Punjab', 'Rajasthan', 'Sikkim',
       'Tamil Nadu', 'Telangana', 'Tripura', 'Uttar Pradesh',
       'Uttarakhand', 'West Bengal', 'A & N Islands', 'Chandigarh',
       'Dadra & Nagar Haveli', 'Daman & Diu', 'Delhi (UT)', 'Lakshadweep',
       'Puducherry'], dtype=object)

- Reference/Master table approach

- Merge State and kidnapping data of 2018

In [1254]:
kidnapping_2018_states = pd.merge(
    States,
    kidnapping_2018,
    on='State',
    how='left'
)

In [1255]:
kidnapping_2018_states

                State   2018
0      Andhra Pradesh   1833
1   Arunachal Pradesh    180
2               Assam   5869
3               Bihar  11257
4        Chhattisgarh   2555
5                 Goa     77
6             Gujarat   2345
7             Haryana   5467
8    Himachal Pradesh    410
9           Jharkhand   4087
10          Karnataka   3175
11             Kerala   1670
12     Madhya Pradesh   8290
13        Maharashtra   7858
14            Manipur    203
15          Meghalaya    122
16            Mizoram     45
17           Nagaland     48
18             Odisha   5336
19             Punjab   2100
20          Rajasthan   5205
21             Sikkim     27
22         Tamil Nadu   2489
23          Telangana   2096
24            Tripura    166
25      Uttar Pradesh  19679
26        Uttarakhand   1379
27        West Bengal   8339

- 2019-2021 kidnapping data

In [1256]:
kidnapping_2019_2021=pd.read_csv(r'Kidnapping_2018_2022/NCRb kidnapping 2019-2021.csv')

In [1257]:
kidnapping_2019_2021.shape

(39, 8)

In [1258]:
kidnapping_2019_2021.head(5)

,Sl. No.,State/UT,2019,2020,2021,Mid-Year Projected Population (in Lakhs) (2021),Rate of Kidnapping & Abduction (2021),Chargesheeting Rate (2021)
0,1,Andhra Pradesh,902.0,737,835,528.5,1.6,71.8
1,2,Arunachal Pradesh,117.0,78,85,15.4,5.5,37.3
2,3,Assam,9432.0,6934,7580,351.6,21.6,30.3
3,4,Bihar,10707.0,7889,10198,1237.0,8.2,53.8
4,5,Chhattisgarh,2638.0,2008,2681,296.1,9.1,36.7

In [1259]:
kidnapping_2019_2021=kidnapping_2019_2021[['State/UT','2019','2020','2021']]

rename column state/ut -> state

In [1260]:
kidnapping_2019_2021.rename(columns={'State/UT':'State'},inplace=True)

In [1261]:
kidnapping_2019_2021

                                       State      2019   2020    2021
0                             Andhra Pradesh     902.0    737     835
1                          Arunachal Pradesh     117.0     78      85
2                                      Assam    9432.0   6934    7580
3                                      Bihar   10707.0   7889   10198
4                               Chhattisgarh    2638.0   2008    2681
5                                        Goa      71.0     45      52
6                                    Gujarat    1813.0   1198    1621
7                                    Haryana    4023.0   2949    3554
8                           Himachal Pradesh     455.0    343     430
9                                  Jharkhand    1814.0   1564    1767
10                                 Karnataka    3080.0   2253    2879
11                                    Kerala     386.0    307     364
12                            Madhya Pradesh    9812.0   7320    9511
13                               Maharashtra   11755.0   8103   10502
14                                   Manipur     129.0     81      85
15                                 Meghalaya     130.0     91     123
16                                   Mizoram       5.0      3       2
17                                  Nagaland      64.0     24      48
18                                    Odisha    4748.0   4179    5625
19                                    Punjab    1798.0   1399    1787
20                                 Rajasthan    8058.0   6234    7717
21                                    Sikkim      51.0     32      39
22                                Tamil Nadu     898.0    765     821
23                                 Telangana    2127.0   2056    2760
24                                   Tripura     166.0    127     136
25                             Uttar Pradesh   16590.0  12913   14554
26                               Uttarakhand     967.0    768     819
27                               West Bengal    5190.0   9309    8339
28                            Total State(S)   97926.0  79709   94914
29               Andaman and Nicobar Islands      27.0      7       7
30                                Chandigarh     177.0    118     154
31  Dadra and Nagar Haveli and Daman and Diu      35.0     21      48
32                                     Delhi    5901.0   4062    5527
33                         Jammu and Kashmir     961.0    868    1013
34                                    Ladakh       NaN      0       4
35                               Lakshadweep       0.0      1       0
36                                Puducherry       9.0     19      40
37                               Total UT(s)    7110.0   5096    6793
38                           Total All India  105036.0  84805  101707

Merge States with kidnapping_2019_2021

In [1262]:
Kidnapping_2019_21_States= pd.merge(States,kidnapping_2019_2021,on='State',how='left')

In [1263]:
Kidnapping_2019_21_States.shape

(28, 4)

 2020-2022 kidnapping data

In [1264]:
k_2020_22=pd.read_csv(r'Kidnapping_2018_2022/kidnapping2021.csv')

In [1265]:
k_2020_22.shape

(39, 8)

In [1266]:
k_2020_22.head(3)

,Sl. No.,State/UT,2020,2021,2022,Mid-Year Projected Population (in Lakhs) (2022),Rate of Kidnapping and Abduction (2022),Chargesheeting Rate (2022)
0,1,Andhra Pradesh,737,835,903,530.3,1.7,62.4
1,2,Arunachal Pradesh,78,85,70,15.5,4.5,39.3
2,3,Assam,6934,7580,4560,354.9,12.8,24.5

feature selection

In [1267]:
k_2020_22=k_2020_22[['State/UT','2020','2021','2022']]

rename column state

In [1268]:
k_2020_22.rename(columns={'State/UT':'State'},inplace=True)

merge 2020-22 kidnapping data with states data

In [1269]:
K_20_22_States=pd.merge(States,k_2020_22,on='State',how='left')

In [1270]:
K_20_22_States.shape

(28, 4)

Merge 5 years kidnapping data

2018 kidnapping data 
2019_21 kidnapping data
2020_22 kidnapping data

2018-2021 kidnapping data of states

In [1271]:
kid_18_21_state=pd.merge(kidnapping_2018_states,Kidnapping_2019_21_States,on='State',how='left')

In [1272]:
kid_18_21_state

                State   2018     2019   2020   2021
0      Andhra Pradesh   1833    902.0    737    835
1   Arunachal Pradesh    180    117.0     78     85
2               Assam   5869   9432.0   6934   7580
3               Bihar  11257  10707.0   7889  10198
4        Chhattisgarh   2555   2638.0   2008   2681
5                 Goa     77     71.0     45     52
6             Gujarat   2345   1813.0   1198   1621
7             Haryana   5467   4023.0   2949   3554
8    Himachal Pradesh    410    455.0    343    430
9           Jharkhand   4087   1814.0   1564   1767
10          Karnataka   3175   3080.0   2253   2879
11             Kerala   1670    386.0    307    364
12     Madhya Pradesh   8290   9812.0   7320   9511
13        Maharashtra   7858  11755.0   8103  10502
14            Manipur    203    129.0     81     85
15          Meghalaya    122    130.0     91    123
16            Mizoram     45      5.0      3      2
17           Nagaland     48     64.0     24     48
18             Odisha   5336   4748.0   4179   5625
19             Punjab   2100   1798.0   1399   1787
20          Rajasthan   5205   8058.0   6234   7717
21             Sikkim     27     51.0     32     39
22         Tamil Nadu   2489    898.0    765    821
23          Telangana   2096   2127.0   2056   2760
24            Tripura    166    166.0    127    136
25      Uttar Pradesh  19679  16590.0  12913  14554
26        Uttarakhand   1379    967.0    768    819
27        West Bengal   8339   5190.0   9309   8339

Retrieve 2022 data separately from k_2020_22 data

In [1273]:
kid_22_states=K_20_22_States[['State','2022']]
kid_22_states

                State   2022
0      Andhra Pradesh    903
1   Arunachal Pradesh     70
2               Assam   4560
3               Bihar  11822
4        Chhattisgarh   2740
5                 Goa     84
6             Gujarat   1846
7             Haryana   3891
8    Himachal Pradesh    413
9           Jharkhand   1899
10          Karnataka   3365
11             Kerala    403
12     Madhya Pradesh  10409
13        Maharashtra  12260
14            Manipur    100
15          Meghalaya    139
16            Mizoram      9
17           Nagaland     28
18             Odisha   5854
19             Punjab   1654
20          Rajasthan   8824
21             Sikkim     46
22         Tamil Nadu    737
23          Telangana   2981
24            Tripura    105
25      Uttar Pradesh  16263
26        Uttarakhand   1169
27        West Bengal   8088

Merge 2018_21 kidnapping data with 2022 kidnapping data of states

In [1274]:
Kidnap_1822_states=pd.merge(kid_18_21_state,kid_22_states,on='State',how='left')

In [1275]:
Kidnap_1822_states

                State   2018     2019   2020   2021   2022
0      Andhra Pradesh   1833    902.0    737    835    903
1   Arunachal Pradesh    180    117.0     78     85     70
2               Assam   5869   9432.0   6934   7580   4560
3               Bihar  11257  10707.0   7889  10198  11822
4        Chhattisgarh   2555   2638.0   2008   2681   2740
5                 Goa     77     71.0     45     52     84
6             Gujarat   2345   1813.0   1198   1621   1846
7             Haryana   5467   4023.0   2949   3554   3891
8    Himachal Pradesh    410    455.0    343    430    413
9           Jharkhand   4087   1814.0   1564   1767   1899
10          Karnataka   3175   3080.0   2253   2879   3365
11             Kerala   1670    386.0    307    364    403
12     Madhya Pradesh   8290   9812.0   7320   9511  10409
13        Maharashtra   7858  11755.0   8103  10502  12260
14            Manipur    203    129.0     81     85    100
15          Meghalaya    122    130.0     91    123    139
16            Mizoram     45      5.0      3      2      9
17           Nagaland     48     64.0     24     48     28
18             Odisha   5336   4748.0   4179   5625   5854
19             Punjab   2100   1798.0   1399   1787   1654
20          Rajasthan   5205   8058.0   6234   7717   8824
21             Sikkim     27     51.0     32     39     46
22         Tamil Nadu   2489    898.0    765    821    737
23          Telangana   2096   2127.0   2056   2760   2981
24            Tripura    166    166.0    127    136    105
25      Uttar Pradesh  19679  16590.0  12913  14554  16263
26        Uttarakhand   1379    967.0    768    819   1169
27        West Bengal   8339   5190.0   9309   8339   8088

convert 2019 data in int type

In [1276]:
Kidnap_1822_states['2019']=Kidnap_1822_states['2019'].astype(int)

Pivot = rows → columns          
Unpivot / Melt = columns → rows ✅

kidnap_2018_2022 - columns- state,2018,2019,2020,2021,2022          
we want, kidnap_data_2018_22- columns: State,Year,Cases

In [1277]:
Kidnap_1822_states = Kidnap_1822_states.melt( 
        id_vars=['State'],var_name='Year',value_name='Kidnapping Cases')

### 5 Years kidnapping data

In [1278]:
Kidnap_1822_states

                 State  Year  Kidnapping Cases
0       Andhra Pradesh  2018              1833
1    Arunachal Pradesh  2018               180
2                Assam  2018              5869
3                Bihar  2018             11257
4         Chhattisgarh  2018              2555
..                 ...   ...               ...
135          Telangana  2022              2981
136            Tripura  2022               105
137      Uttar Pradesh  2022             16263
138        Uttarakhand  2022              1169
139        West Bengal  2022              8088

[140 rows x 3 columns]

In [1279]:
print("Before saving:", Kidnap_1822_states.shape)
Kidnap_1822_states.to_csv("kidnapping_data_states_2018_2022.csv", index=False)

Before saving: (140, 3)

## Merge kidnapping data

In [1286]:
Rapecases5year_states_population.head(2)

            State  Population  Rape Cases  Year
0  Andhra Pradesh    49577103         971  2018
1  Andhra Pradesh    49577103        1086  2019

In [1287]:
Kidnap_1822_states.head(2)

               State  Year  Kidnapping Cases
0     Andhra Pradesh  2018              1833
1  Arunachal Pradesh  2018               180

both rape and kidnapping data have 2 common column state and year

check column data type before merging

In [1282]:
Rapecases5year_states_population['Year'].dtype

dtype('int64')

In [1284]:
Kidnap_1822_states['Year'].dtype

dtype('O')

change data type of Year column

In [1285]:
Kidnap_1822_states['Year'] = Kidnap_1822_states['Year'].astype(int)

Merge both data

In [1291]:
Women_Safety_Risk_Analysis = pd.merge(
    Rapecases5year_states_population,
    Kidnap_1822_states,
    on=['State', 'Year'],
    how='left'
)

# **Final Integrated Data**

In [1293]:
Women_Safety_Risk_Analysis.to_csv("Women_Safety_Risk_Analysis.csv", index=False)
Women_Safety_Risk_Analysis

              State  Population  Rape Cases  Year  Kidnapping Cases
0    Andhra Pradesh    49577103         971  2018              1833
1    Andhra Pradesh    49577103        1086  2019               902
2    Andhra Pradesh    49577103        1095  2020               737
3    Andhra Pradesh    49577103        1188  2021               835
4    Andhra Pradesh    49577103         621  2022               903
..              ...         ...         ...   ...               ...
135     West Bengal    91276115        1069  2018              8339
136     West Bengal    91276115        1069  2019              5190
137     West Bengal    91276115        1128  2020              9309
138     West Bengal    91276115        1123  2021              8339
139     West Bengal    91276115        1111  2022              8088

[140 rows x 5 columns]